{{- if .Values.apiServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "driftlock.fullname" . }}-api-server
  labels:
    {{- include "driftlock.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
  - port: {{ .Values.apiServer.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.apiServer.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "driftlock.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
{{- end }}
---
{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "driftlock.fullname" . }}-ui
  labels:
    {{- include "driftlock.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "driftlock.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}
