name = "driftlock-playground"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[env.production]
name = "driftlock-playground"

[env.preview]
name = "driftlock-playground-preview"

