name = "driftlock-landing"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[env.production]
name = "driftlock-landing"

[env.preview]
name = "driftlock-landing-preview"